services:
  postgres:
    image: postgres:15
    container_name: market_pulse_db
    environment:
      POSTGRES_USER: engineer
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: market_pulse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ingestor:
    build: .
    container_name: market_pulse_ingestor
    depends_on:
      - postgres

    environment:
      - DB_HOST=postgres
      - DB_NAME=market_pulse
      - DB_USER=engineer
      - DB_PASSWORD=password123
      - DB_PORT=5432

volumes:
  postgres_data:
