version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: market_pulse_db
    environment:
      POSTGRES_USER: engineer
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: market_pulse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
